name: Test project skeleton

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  create-project:
    runs-on: "ubuntu-latest"

    steps:
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/fermium
      - name: Run composer create-project
        shell: bash -l {0}
        run: composer create-project --no-progress --stability=dev sumocoders/application-skeleton:dev-master test