name: Test project skeleton

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  create-project:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: lts/fermium
    - run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
    - run: nvm install lts/fermium
    - run: composer create-project --no-progress --stability=dev sumocoders/application-skeleton:dev-master test